IKIGAI_hastanesi/Controllers/doktorController.cs
using IKIGAI_hastanesi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKIGAI_hastanesi.Controllers
{
    public class doktorController : Controller
    {
        // GET: doktor
        public ActionResult index()
        {
            return View();
        }
        public ActionResult records()
        {
            return View();
        }


        [HttpGet]
        public ActionResult doctorsignin()
        {
            return View(new doktorlogin());
        }
        [HttpPost]
        public ActionResult doctorsignin(doktorlogin doktorlogin)
        {
            Modelcontext context = new Modelcontext();
            context.doktorlogin.Add(doktorlogin);
            context.SaveChanges();
            return RedirectToAction("doctorlogin");
        }
        [HttpGet]
        public ActionResult doctorlogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult doctorlogin(string doktortc, string doktorsifre)
        {
            Modelcontext context = new Modelcontext();
            var doktorvarmi = context.doktorlogin.Where(o => o.doktortc == doktortc && o.doktorsifre == doktorsifre).FirstOrDefault();

            if (doktorvarmi != null)
            {
                Session["doktorlogin"] = doktorvarmi;
                return RedirectToAction("index");
            }
            else
            {
                ViewBag.hata = "Geçersiz TC veya şifre";
                return View();
            }

        }

        [HttpGet]
        public ActionResult infopattient()
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist = context.hasta.ToList();
            return View(Hastalist);
        }

        [HttpPost]
        public ActionResult infopattient(string aranan)
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist = context.hasta.Where(x => x.hastaad.Contains(aranan) ||
            x.hastasoyad.Contains(aranan) ||
            x.hastatc.Contains(aranan) ||
            x.hastadogum.Contains(aranan) ||
            x.hastabolum.Contains(aranan)
            ).ToList();
            return View(Hastalist);
        }


        [HttpGet]
        public ActionResult delete(int id)
        {
            Modelcontext context = new Modelcontext();
            var hastasil = context.hasta.Where(x => x.hastaid == id).FirstOrDefault();
            context.hasta.Remove(hastasil);
            context.SaveChanges();
            return RedirectToAction("infopattient");


        }

        [HttpGet]
        public ActionResult updated(int id)
        {
            Modelcontext context = new Modelcontext();
            var hastaguncelle = context.hasta.Where(x => x.hastaid == id).FirstOrDefault();
            return View(hastaguncelle);


        }
        [HttpPost]
        public ActionResult updated(hasta hasta)
        {

            Modelcontext context = new Modelcontext();
            var hastaguncelle = context.hasta.Where(x => x.hastaid == hasta.hastaid).FirstOrDefault();
            hastaguncelle.hastaad = hasta.hastaad;
            hastaguncelle.hastasoyad = hasta.hastasoyad;
            hastaguncelle.hastatc = hasta.hastatc;
            hastaguncelle.hastadogum = hasta.hastadogum;
            hastaguncelle.hastabolum = hasta.hastabolum;

            context.SaveChanges();
            return RedirectToAction("infopattient");
        }


        [HttpGet]
        public ActionResult tahlil()
        {
            return View(new hastasonuc());
        }

        [HttpPost]
        public ActionResult tahlil(hastasonuc hastasonuc)
        {
            Modelcontext context = new Modelcontext();
            context.hastasonuc.Add(hastasonuc);
            context.SaveChanges();
            return RedirectToAction("allpattient");
        }




        [HttpGet]
        public ActionResult allpattient()
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult allpattient(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||
            x.hastatc.Contains(arananlar) ||
            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar) ||
             x.hastateshis.Contains(arananlar) ||
            x.hastailac.Contains(arananlar) ||
            x.lab.Contains(arananlar) ||
            x.ameliyat.Contains(arananlar) ||
            x.ucreta.Contains(arananlar) ||
            x.ucretlab.Contains(arananlar)
            ).ToList();
            return View(Hastalist1);
        }

        [HttpGet]
        public ActionResult listele()
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist1 = context.hasta.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult listele(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist1 = context.hasta.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||
            x.hastatc.Contains(arananlar) ||
            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar) 
            
            ).ToList();
            return View(Hastalist1);
        }

        [HttpGet]
        public ActionResult updated1(int id)
        {
            Modelcontext context = new Modelcontext();
            var hastaguncelle = context.hastasonuc.Where(x => x.hastasonucid == id).FirstOrDefault();
            return View(hastaguncelle);


        }
        [HttpPost]
        public ActionResult updated1(hastasonuc hastasonuc)
        {

            Modelcontext context = new Modelcontext();
            var hastaguncelle = context.hastasonuc.Where(x => x.hastasonucid == hastasonuc.hastasonucid).FirstOrDefault();
            hastaguncelle.hastaad = hastasonuc.hastaad;
            hastaguncelle.hastasoyad = hastasonuc.hastasoyad;
            hastaguncelle.hastatc = hastasonuc.hastatc;
            hastaguncelle.hastadogum = hastasonuc.hastadogum;
            hastaguncelle.hastabolum = hastasonuc.hastabolum;
            hastaguncelle.hastadoktor = hastasonuc.hastadoktor;
            hastaguncelle.hastateshis = hastasonuc.hastateshis;
            hastaguncelle.hastailac = hastasonuc.hastailac;
            hastaguncelle.lab = hastasonuc.lab;
            hastaguncelle.ameliyat = hastasonuc.ameliyat;
            hastaguncelle.ucreta = hastasonuc.ucreta;
            hastaguncelle.ucretlab = hastasonuc.ucretlab;


            context.SaveChanges();
            return RedirectToAction("allpattient");
        }

        [HttpGet]
        public ActionResult delete1(int id)
        {
            Modelcontext context = new Modelcontext();
            var hastasil = context.hastasonuc.Where(x => x.hastasonucid == id).FirstOrDefault();
            context.hastasonuc.Remove(hastasil);
            context.SaveChanges();
            return RedirectToAction("allpattient");


        }

        [HttpGet]
        public ActionResult addpattient1()
        {
            if (Session["doktorlogin"] == null)
            {
                return RedirectToAction("doctorlogin");
            }
            else
            {
                Modelcontext context = new Modelcontext();
                List<hasta> hasta = context.hasta.ToList();
                return View(hasta);
            }
        }
        public ActionResult doctorselect(int id)
        {
            if (Session["doktorlogin"] == null)
            {
                return RedirectToAction("doctorlogin");
            }
            else
            {
                Modelcontext context = new Modelcontext();
                doktorlogin doktorlogin = (doktorlogin)Session["doktorlogin"];

                hepsi hepsitablo = new hepsi();
                {
                    hepsitablo.doktorid = doktorlogin.doktorid;
                    hepsitablo.hastaid = id;
                };

                context.hepsi.Add(hepsitablo);
                context.SaveChanges();
                return RedirectToAction("listpattient1");
            }
        }
        [HttpPost]
        public ActionResult addpattient1(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist1 = context.hasta.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||
            x.hastatc.Contains(arananlar) ||
            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar)

            ).ToList();
            return View(Hastalist1);
        }

        [HttpGet]
        public ActionResult listpattient1()
        {
            if (Session["doktorlogin"] == null)
            {
                return RedirectToAction("doctorlogin");
            }
            else
            {
                Modelcontext context = new Modelcontext();
                doktorlogin doktorlogin = (doktorlogin)Session["doktorlogin"];

                List<hepsi> hepsi = context.hepsi.Where(x => x.doktorid == doktorlogin.doktorid).ToList();


                return View(hepsi);
            }
        }

        [HttpGet]
        public ActionResult exportexcel()
        {
            Modelcontext context = new Modelcontext();
            List<hasta> Hastalist1 = context.hasta.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult exportexcel(string arananlar)
        {
            Modelcontext context = new Modelcontext();

IKIGAI_hastanesi/Controllers/homeController.cs
using IKIGAI_hastanesi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IKIGAI_hastanesi.Controllers
{
    public class homeController : Controller
    {
        // GET: home


        public ActionResult index()
        {
            return View();
        }

    

        public ActionResult about()
        {
            return View();
        }
        public ActionResult records()
        {
            return View();
        }


        public ActionResult contact()
        {
            return View();
        }


        //[HttpGet]
        //public ActionResult doctorsignin ()
        //{
        //    return View(new doktorlogin());
        //}
        //[HttpPost]
        //public ActionResult doctorsignin(doktorlogin doktorlogin)
        //{
        //    Modelcontext context = new Modelcontext();
        //    context.doktorlogin.Add(doktorlogin);
        //    context.SaveChanges();
        //    return RedirectToAction("doctorlogin");
        //}


        [HttpGet]
        public ActionResult appointment()
        {
            return View(new hasta());
        }

        [HttpPost]
        public ActionResult appointment( hasta hasta)
        {
            Modelcontext context = new Modelcontext();
            context.hasta.Add(hasta);
            context.SaveChanges();
            return RedirectToAction("index");
        }

        [HttpGet]
        public ActionResult teshisler()
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult teshisler(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||
            
            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar) ||
            x.hastadoktor.Contains(arananlar) ||
             x.hastateshis.Contains(arananlar) ||
            x.hastailac.Contains(arananlar)
            ).ToList();
            return View(Hastalist1);
        }

        [HttpGet]
        public ActionResult labaratuvar()
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult labaratuvar(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||

            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar) ||
            x.hastadoktor.Contains(arananlar) ||
             x.lab.Contains(arananlar) ||
            x.ameliyat.Contains(arananlar)
            ).ToList();
            return View(Hastalist1);
        }

        [HttpGet]
        public ActionResult ucretler()
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.ToList();
            return View(Hastalist1);
        }

        [HttpPost]
        public ActionResult ucretler(string arananlar)
        {
            Modelcontext context = new Modelcontext();
            List<hastasonuc> Hastalist1 = context.hastasonuc.Where(x => x.hastaad.Contains(arananlar) ||
            x.hastasoyad.Contains(arananlar) ||

            x.hastadogum.Contains(arananlar) ||
            x.hastabolum.Contains(arananlar) ||
            x.hastadoktor.Contains(arananlar) ||
             x.ucreta.Contains(arananlar) ||
            x.ucretlab.Contains(arananlar)
            ).ToList();
            return View(Hastalist1);
        }



    }
}
         
  




    
    

IKIGAI_hastanesi/Views/shared/_LayoutPage1.cshtml
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> IKIGAI </title>

    <link rel="shortcut icon" href="~/Content/assets/images/fav.jpg">
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/fontawsom-all.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/style.css" />




  




</head>

<body>

    <!-- ################# Header Starts Here#######################--->
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul>
                            <li><i class="fas fa-envelope-square"></i> ikigai@hospital.com</li>
                            <li><i class="fas fa-phone-square"></i> 0380 556 00 00</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <li><a><i class="fab fa-github"></i></a></li>
                            <li><a><i class="fab fa-google-plus-g"></i></a></li>
                            <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                            <li><a><i class="fab fa-twitter"></i></a></li>
                            <li> <a><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div id="nav-head" class="header-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-12 nav-img">
                        <a href="/home/index" target="_self">   <img src="/Content/assets/images/new.jpg" alt="" style="width:70%;"> </a>
                        <a data-toggle="collapse" data-target="#menu" href="#menu"><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                    </div>
                    <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                        <ul>
                            <li>@Html.ActionLink("Anasayfa", "index", "home")</li>
                            <li>@Html.ActionLink("Hakkında", "about", "home")</li>
                            <li>@Html.ActionLink("Kayıtlar", "records", "home")</li>
                            <li>@Html.ActionLink("Randevu Al", "appointment", "home")</li>
                            <li>@Html.ActionLink("İletişim", "contact", "home")</li>

                        </ul>
                    </div>
                </div>

            </div>
        </div>

    </header>




    @RenderBody()


    <!-- ################# Footer Starts Here#######################--->
    <!--  ************************* Page Title Starts Here ************************** -->
    <div class="page-nav no-margin row">
        <div class="container">
            <div class="row">
                <h2></h2>
                <ul>
                    <li> <a href=""><i class=""></i> </a></li>
                    <li><i class=""></i> </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="copy">
        <div class="container">
            <a href="#">2022 &copy; TÜM HAKLARI SINIRLIDIR | Designed and Developed by GEU SOFT &nbsp;</a>

            <span>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-google-plus-g"></i></a>
                <a><i class="fab fa-pinterest-p"></i></a>
                <a><i class="fab fa-twitter"></i></a>
                <a><i class="fab fa-facebook-f"></i></a>
            </span>
        </div>

    </div>

</body>

<script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/assets/js/popper.min.js"></script>
<script src="~/Content/assets/js/bootstrap.min.js"></script>
<script src="~/Content/assets/plugins/scroll-fixed/jquery-scrolltofixed-min.js"></script>
<script src="~/Content/assets/js/script.js"></script>



</html>

IKIGAI_hastanesi/Views/shared/_doktorLayout.cshtml
@{ 
    IKIGAI_hastanesi.Models.doktorlogin doktorlogin = (IKIGAI_hastanesi.Models.doktorlogin)Session["doktorlogin"];
}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> IKIGAI </title>

    <link rel="shortcut icon" href="~/Content/assets/images/fav.jpg">
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/fontawsom-all.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/style.css" />









</head>

<body>

    <!-- ################# Header Starts Here#######################--->
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul>
                            <li><i class="fas fa-envelope-square"></i> ikigai@hospital.com</li>
                            <li><i class="fas fa-phone-square"></i> 0380 556 00 00</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <p style="font-size:15px; font-weight:bold; color:white; border:1px solid white; padding:7px; margin:7px;"> @doktorlogin.doktorad @doktorlogin.doktorsoyad  <a href="/home/index"style="font-size:15px; font-weight:bold; color:white; border:1px solid white; padding:7px;"> ÇIKIŞ </a></p> 
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div id="nav-head" class="header-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-12 nav-img">
                        <a href="/doktor/index" target="_self">   <img src="/Content/assets/images/new.jpg" alt="" style="width:70%;"> </a>
                        <a data-toggle="collapse" data-target="#menu" href="#menu"><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                    </div>
                    <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                        <ul>
                            <li>@Html.ActionLink("Anasayfa", "index", "doktor")</li>

                            <li>@Html.ActionLink("Hasta Bilgileri Giriş", "records", "doktor")</li>

                            <li>@Html.ActionLink("Hastayı Ekle", "addpattient1", "doktor")</li>

                            <li>@Html.ActionLink("Hastayı Listele", "listpattient1", "doktor")</li>




                        </ul>
                    </div>
                </div>

            </div>
        </div>

    </header>




    @RenderBody()


    <!-- ################# Footer Starts Here#######################--->
    <!-- ################# Our Team Starts Here#######################--->
    <!--  ************************* Page Title Starts Here ************************** -->
    <div class="page-nav no-margin row">
        <div class="container">
            <div class="row">
                <h2></h2>
                <ul>
                    <li> <a href=""><i class=""></i> </a></li>
                    <li><i class=""></i> </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- ######## Page  Title End ####### -->


    <div class="copy">
        <div class="container">
            <a href="#">2022 &copy; TÜM HAKLARI SINIRLIDIR | Designed and Developed by GEU SOFT &nbsp;</a>

            <span>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-google-plus-g"></i></a>
                <a><i class="fab fa-pinterest-p"></i></a>
                <a><i class="fab fa-twitter"></i></a>
                <a><i class="fab fa-facebook-f"></i></a>
            </span>
        </div>

    </div>

</body>

<script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/assets/js/popper.min.js"></script>
<script src="~/Content/assets/js/bootstrap.min.js"></script>
<script src="~/Content/assets/plugins/scroll-fixed/jquery-scrolltofixed-min.js"></script>
<script src="~/Content/assets/js/script.js"></script>



</html>